FORMAT: X-1A
HOST: https://api.transdirect.com.au/

# Transdirect Public API V3

This is a WIP API for Transdirect.

Authentication is via HTTP basic authentication. API is only accessible via HTTPS.

Error codes: 200 201 304 400 401 403 404 415 500

Formats: JSON only including input - 415 error on invalid content types.

# Group Locations
A location is a unique postcode/suburb combination. A suburb might have multiple locations with different postcodes
and similarly a postcode will have many locations for each suburb within the postcode.


# Group Bookings
Get a quick quote, this will return a booking id that can be further updated with sender, receiver and other shipping options

# Booking [/bookings{?since,order}]

## Create a booking or get a quick quote [POST]
At a minimum the body must contain the fields below. Following creation you can update the booking from the
returned booking id by using the PUT or PATCH methods.

The `country` field in `from`/`to` is set to "AU" by default.

+ Request (application/json)

    + Body 
        
        ```js
        {
            "insuranceValue" : 10000,
            "items": [
                {
                    "weight": 100,
                    "height": 100,
                    "width": 100,
                    "depth": 100,
                    "quantity": 1,
                    "unit": "pallet"
                },
                {
                    "weight": 10,
                    "height": 10,
                    "width": 10,
                    "depth": 10,
                    "quantity": 5,
                    "unit": "carton"
                }  
            ],
            "from": {
                "country" : "AU",
                "postCode": "2000",
                "type": "residential"
            },
            "to": {
                "country" : "AU",
                "postCode": "3000",
                "type": "business"
            },
            "dangerousGoods": false
        }
        ```

+ Response 201 (application/json)

    + Headers  
    
        ```
        Location: /bookings/{bookingId}
        ```
    
    + Body 
        
        ```js
        {
            "id" : 232456,
            "dangerousGoods" : false,
            "items" : [
                {
                    "id" : 523456,
                    "weight" : 100,
                    "height" : 100,
                    "width" : 100,
                    "depth" : 100,
                    "quantity" : 1,
                    "unit" : "pallet"
                },
                {
                    "id" : 523459,
                    "weight" : 10,
                    "height" : 10,
                    "width" : 10,
                    "depth" : 10,
                    "quantity" : 5,
                    "unit" : "carton"
                }  
            ],
            "notifications": {
                "email": true,
                "sms": false
            },
            "from": {
                "country" : "AU",
                "postCode": "2000",
                "type": "residential"
            },
            "to": {
                "country" : "AU",
                "postCode": "3000",
                "type": "business"
            },
            "quotes": {
                "toll" : 47.87,
                "allied" : 56.97,
                "couriersplease" : 53.65
            },
            "payment": {
                "status": "unpaid"
            },
            "status" : "quoted",
            "createdAt" : "2013-10-26T18:24:02Z",
            "updatedAt" : "2013-10-26T18:24:02Z"
        }
        ```


## Get all your bookings [GET]

+ Parameters

    + since (optional, string) ... Timestamp in ISO 8601 format: `YYYY-MM-DDTHH:MM:SSZ` Only bookings created at or after this time are returned.
    + order (optional, string) ... The sort order of the bookings returned. Default is `createdAt`, options are `price`, `updatedAt`
    
    
+ Response 201 (application/json)

    + Body 
        
        ```js
        {
            "id" : 232456,
            "dangerousGoods": false,
            "from": {
                "postcode": "2000",
                "type": "residential"
            },
            "items": [
                {
                    "weight": 100,
                    "height": 100,
                    "width": 100,
                    "depth": 100,
                    "quantity": 1,
                    "unit": "pallet"
                },
                {
                    "weight": 10,
                    "height": 10,
                    "width": 10,
                    "depth": 10,
                    "quantity": 5,
                    "unit": "carton"
                }  
            ],
            "notifications": {
                "email": true,
                "sms": false
            },
            "to": {
                "postcode": "3000",
                "type": "business"
            },
            "quotes": {
                "toll" : 47.87,
                "allied" : 56.97,
                "couriersplease" : 53.65
            },
            "payment": {
                "status": "unpaid"
            },
            "status" : "quoted"
        }
        ```
    
# Booking [/bookings/{id}]

## Get a single booking [GET]

## Update a booking [PUT]

## Partially update a booking [PATCH]

# Booking Items [/bookings/{id}/items]



## Get all items in a booking [GET]

+ Response 200 (application/json)
 
   ```js
    [
        {
            "weight": 100,
            "height": 100,
            "width": 100,
            "depth": 100,
            "quantity": 1,
            "unit": "pallet"
        },
        {
            "weight": 10,
            "height": 10,
            "width": 10,
            "depth": 10,
            "quantity": 5,
            "unit": "carton"
        }  
    ]
    ```
    

## Add an item to a booking [POST]
Todo: do we need an id in the response?

+ Response 201 (application/json)
 
    + Headers  
    
        ```
        Location: /bookings/{bookingId}/item/{itemId}
        ```
    
    + Body 
    
       ```js
        {
            "weight": 20,
            "height": 30,
            "width": 10,
            "depth": 10,
            "quantity": 5,
            "unit": "carton"
        }
        ```


# Booking Items [/bookings/{id}/label]

## GET /bookings/{id}/label
Get the PDF label for a booking

+ Response 200 (application/pdf)
 
    + Headers  
    
        ```
        Location: /bookings/{bookingId}/item/{itemId}
        ```
    
    + Body 
    
       ```js
        {
            "weight": 20,
            "height": 30,
            "width": 10,
            "depth": 10,
            "quantity": 5,
            "unit": "carton"
        }
        ```

+ Response 201 (application/pdf)


## PUT /bookings/{bookingId}/payment
Pay for a booking - fields TBC


-- Members Resources --

Get the current member - should return full account info (balance etc)
GET /member
> Accept: application/json
< 200
< Content-Type: application/json
{
    "member": {
        "name": "John Smith",
        "company": "Test Company",
        "email": "john@example.com",
        "address": "",
        "suburb": "",
        "postcode": "",
        "state": "NSW",
        "phone": "02 9999 9999",
        "discountFactor": 0.05,
        "creditLimit": 5000,
        "creditLimitAvailable": 4355.34,
        "chargeType": "invoice",
        "terms": 30,
        "active": true
    },
    "meta": {
        "code": 200
    }
}

Get a members bookings
GET /members/{memberId}/bookings{?limit,offset,orderBy}
> Accept: application/json
< 200
< Content-Type: application/json
[]

Get a members address book
GET /members/{memberId}/addresses{?limit,offset,orderBy}
> Accept: application/json
< 200
< Content-Type: application/json
{
    "addresses": [
        {
            "id": 65543,
            "address": "10 Test Street",
            "suburb": "Darlinghurst",
            "state": "NSW",
            "postcode": "2010"
        },
        {
            "id": 66643,
            "address": "20 Test Street",
            "suburb": "Darlinghurst",
            "state": "NSW",
            "postcode": "2010"
        }
    ],
    "links": {},
    "meta": {}
}

Create a new entry in the members address book
POST /members/{memberId}/addresses
> Accept: application/json
< 201
< Content-Type: application/json
< Location: /members/{memberId}/addresses/{addressId}
[]

Get a single address from address book
GET /members/{memberId}/addresses/{addressId}
> Accept: application/json
< 200
< Content-Type: application/json
{
    "address": {
        "id": 65543,
        "address": "10 Test Street",
        "suburb": "Darlinghurst",
        "state": "NSW",
        "postcode": "2010"
    },
    "meta": {}
}

Get monthly statements
GET /members/{memberId}/statements{?limit,offset,orderBy}
> Accept: application/json
< 200
< Content-Type: application/json
[]

Get single monthly statement
GET /members/{memberId}/statements/{statementId}
> Accept: application/json
< 200
< Content-Type: application/json
[]

-- Locations Resources --

Get all locations.
GET /locations
> Accept: application/json
< 200
< Content-Type: application/json
{
    "locations": [
        {
            "locality": "SYDNEY",
            "pcode": "1001",
            "state": "NSW"
        },
        {
            "locality": "SYDNEY",
            "pcode": "1002",
            "state": "NSW"
        },
        {
            "locality": "SYDNEY",
            "pcode": "1003",
            "state": "NSW"
        },
        {
            "locality": "SYDNEY",
            "pcode": "1004",
            "state": "NSW"
        },
        {
            "locality": "SYDNEY",
            "pcode": "1005",
            "state": "NSW"
        }
    ],
    "links": {
        "first": "http://api.transdirect.com.au/locations?page=1",
        "previous": "http://api.transdirect.com.au/locations?page=1",
        "next": "http://api.transdirect.com.au/locations?page=3",
        "last": "http://api.transdirect.com.au/locations?page=123"
    },
    "meta": {
        "count": 20123,
        "code": 200,
        "message": ""
    }
}

Search all locations.
GET /locations{?searchTerm}
> Accept: application/json
< 200
< Content-Type: application/json
{
    "locations": [
        {
            "locality": "SYDNEY",
            "pcode": "1001",
            "state": "NSW"
        },
        {
            "locality": "SYDNEY",
            "pcode": "1002",
            "state": "NSW"
        },
        {
            "locality": "SYDNEY",
            "pcode": "1003",
            "state": "NSW"
        },
        {
            "locality": "SYDNEY",
            "pcode": "1004",
            "state": "NSW"
        },
        {
            "locality": "SYDNEY",
            "pcode": "1005",
            "state": "NSW"
        }
    ],
    "links": {},
    "meta": {
        "count": 5,
        "limit": 10,
        "offset": 0,
        "query": "sydn",
        "code": 200,
        "message": ""
    }
}

Get all locations available. Please note this data is for use in typeaheads etc and may not be 100% accurate for all 
couriers as each has their own postcode and suburb data.
GET /locations/postcode/{postcode}
> Accept: application/json
< 200
< Content-Type: application/json
{
    "locations": [
        {
            "locality": "BARANGAROO",
            "pcode": "2000",
            "state": "NSW"
        },
        {
            "locality": "DAWES POINT",
            "pcode": "2000",
            "state": "NSW"
        },
        {
            "locality": "HAYMARKET",
            "pcode": "2000",
            "state": "NSW"
        },
        {
            "locality": "MILLERS POINT",
            "pcode": "2000",
            "state": "NSW"
        },
        {
            "locality": "PARLIAMENT HOUSE",
            "pcode": "2000",
            "state": "NSW"
        },
        {
            "locality": "SYDNEY",
            "pcode": "2000",
            "state": "NSW"
        },
        {
            "locality": "SYDNEY SOUTH",
            "pcode": "2000",
            "state": "NSW"
        },
        {
            "locality": "THE ROCKS",
            "pcode": "2000",
            "state": "NSW"
        }
    ],
    "meta": {
        "count": 8,
        "code": 200,
        "postcode": "2000"
    }
}


